### ISSUE TITLE
Troubles with DNS resolution

### ISSUE THREAD

**Issue by kud** [jsdelivr/jsdelivr#18164]
Hello,

I'm sorry if I won't be clear because the problem isn't a subject I master a lot.

One of our users has some troubles to reach your servers.

What he told me:

> cdn\.jsdelivr\.net answers NXDOMAIN when we activate QNAME minimisation (the server answers NXDOMAIN for ENT (Empty Non-Terminal))

The test:

```
 dig @ns1.flexbalancer.net. A a7e454.flexbalancer.net 

; <<>> DiG 9.10.3-P4-Debian <<>> @ns1.flexbalancer.net. A a7e454.flexbalancer.net
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 627
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 512
;; QUESTION SECTION:
;a7e454.flexbalancer.net. IN A

;; Query time: 20 msec
;; SERVER: 2400:cb00:2049:1::a29f:18a3#53(2400:cb00:2049:1::a29f:18a3)
;; WHEN: Wed Jul 31 12:16:34 CEST 2019
;; MSG SIZE  rcvd: 52

% dig @ns1.flexbalancer.net. A jsdelivr.a7e454.flexbalancer.net

; <<>> DiG 9.10.3-P4-Debian <<>> @ns1.flexbalancer.net. A jsdelivr.a7e454.flexbalancer.net
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17070
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 512
;; QUESTION SECTION:
;jsdelivr.a7e454.flexbalancer.net. IN A

;; ANSWER SECTION:
jsdelivr.a7e454.flexbalancer.net. 10 IN	CNAME dualstack.f3.shared.global.fastly.net.

;; Query time: 20 msec
;; SERVER: 2400:cb00:2049:1::a29f:18a3#53(2400:cb00:2049:1::a29f:18a3)
;; WHEN: Wed Jul 31 12:17:37 CEST 2019
;; MSG SIZE  rcvd: 109
```

It's apparently not normal.

Could you try to fix this? If you need more information, do not hesitate to ask me. :)

**Comment by jimaek** [comment]
May I ask where the user with the issue is located?

**Comment by kud** [comment]
France!

**Comment by bortzmeyer** [comment]
> May I ask where the user with the issue is located?

This is irrelevant since you can see by yourself (using the dig queries mentioned) that it happens everywhere. (I tested in Japan and in the USA.)

**Comment by jimaek** [comment]
Can you give me some more information? How exactly are they enabling qname minimization? I want to replicate the issue

**Comment by bortzmeyer** [comment]
> Can you give me some more information? How exactly are they enabling qname minimization? I want to replicate the issue

Configuration of my resolver (Unbound):

```
server:
    # Send minimum amount of information to upstream servers to enhance
    # privacy. Only sends minimum required labels of the QNAME and sets
    # QTYPE to NS when possible.
    # See RFC 7816 "DNS Query Name Minimisation to Improve Privacy" for
    # details.
    qname-minimisation: yes
    # If you use this, you also need the above
    qname-minimisation-strict: yes
```
