### ISSUE TITLE
Purge using the jsdelivr web page doesn't seem to purge the cache

### ISSUE THREAD

**Issue by baptisteArno** [jsdelivr/jsdelivr#18495]
### Description

I'm using https://www.jsdelivr.com/tools/purge to purge my aliased version.

It always says that it effectively purged the cache:

<img width="976" alt="CleanShot 2023-05-18 at 09 05 58@2x" src="https://github.com/jsdelivr/jsdelivr/assets/16015833/0ce040eb-4d24-4cee-b922-da90b90ba11e">

But then when I load the script, it's not updated right away. I often need to wait for ~2 hours or more. Is it expected?

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/@typebot.io/js@0.0/dist/web.js

### Response headers

-

### Information

-

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
The file should update right after a successful purge. Unfortunately, I can't say why this might not be the case without more information. If you see the issue again, please post full response headers that you got after a successful purge.

**Comment by baptisteArno** [comment]
Is the purging web tool showing the response headers? Should I inspect it from the networks tab?

**Comment by MartinKolarik** [comment]
I meant headers for the CDN file that is still outdated after the purge (and yes, from network tab).

**Comment by realodix** [comment]
I'm trying to purge the cache on this file and the file not update right after a successful purge

https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt

<details>
  <summary>Response header</summary>
  
```
HTTP/2 200 OK
date: Fri, 16 Jun 2023 12:55:09 GMT
content-type: image/x-icon
cache-control: public, max-age=31536000
etag: W/"1536-I2gXux9vPOs5yfMlZdgosG1aC4M"
x-served-by: cache-fra-eddf8230089-FRA, cache-jnb7023-JNB
x-cache: HIT, MISS
vary: Accept-Encoding
cf-cache-status: HIT
age: 4062716
nel: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 7d83349aeef73579-CGK
content-encoding: br
X-Firefox-Spdy: h2
```
</details>

**Comment by jimaek** [comment]
You need to start tagging your releases for purge to work properly https://github.com/realodix/AdBlockID/tags
Tags are used to identify when the system needs to ask github for new files

**Comment by realodix** [comment]
> You need to start tagging your releases for purge to work properly https://github.com/realodix/AdBlockID/tags Tags are used to identify when the system needs to ask github for new files

I've created a tag, then purge the cache and the file not update right after a successful purge

- https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt
- https://github.com/realodix/AdBlockID/tags

**Comment by jimaek** [comment]
What CDN are you hitting? You can check by looking at the HTTP headers. I am getting the correct latest version at the moment

**Comment by realodix** [comment]
Without VPN, Jakarta, Indonesia
Uncorrect latest version at the moment

<details>
  <summary>response header</summary>

``` yaml
Access-Control-Allow-Origin:
*
Access-Control-Expose-Headers:
*
Age:
41229
Alt-Svc:
h3=":443"; ma=86400
Cache-Control:
public, max-age=604800, s-maxage=43200
Cf-Cache-Status:
HIT
Cf-Ray:
7e385a766bdf3573-CGK
Content-Encoding:
br
Content-Type:
text/plain; charset=utf-8
Cross-Origin-Resource-Policy:
cross-origin
Date:
Sat, 08 Jul 2023 12:33:02 GMT
Etag:
W/"39805-1r3E+g7zXfkpoL9iR1psSzydi0g"
Nel:
{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
Report-To:
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=rwyd5%2F7BQcKYQepAAPvpax%2BlTNkIdYgkCtOyhmIv7X4TzTYPDwiV%2Fo435RE4HVkM0l6R9zEEnl33duzPIX20SJKMtlDVR9Htzl9W0Pzxheykzk8gLOOrYhY%2BdicAAYIWYGxtv6RU0eLbd1AOqX8%3D"}],"group":"cf-nel","max_age":604800}
Server:
cloudflare
Strict-Transport-Security:
max-age=31536000; includeSubDomains; preload
Timing-Allow-Origin:
*
Vary:
Accept-Encoding
X-Cache:
MISS, MISS
X-Content-Type-Options:
nosniff
X-Jsd-Version:
master
X-Jsd-Version-Type:
branch
X-Served-By:
cache-fra-eddf8230049-FRA, cache-jnb7023-JNB
```
</details>


VPN, Singapore
Correct latest version at the moment

<details>
  <summary>response header</summary>

``` yaml
Accept-Ranges:
bytes
Access-Control-Allow-Origin:
*
Access-Control-Expose-Headers:
*
Age:
30577
Alt-Svc:
h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
Cache-Control:
public, max-age=604800, s-maxage=43200
Content-Encoding:
br
Content-Length:
67458
Content-Type:
text/plain; charset=utf-8
Cross-Origin-Resource-Policy:
cross-origin
Date:
Sat, 08 Jul 2023 12:36:03 GMT
Etag:
W/"398e3-+mREWQBD3Mof2qvguCrxjnqhuxs"
Strict-Transport-Security:
max-age=31536000; includeSubDomains; preload

Timing-Allow-Origin:
*
Vary:
Accept-Encoding
X-Cache:
HIT, MISS
X-Content-Type-Options:
nosniff
X-Jsd-Version:
23.7.28
X-Jsd-Version-Type:
version
X-Served-By:
cache-fra-eddf8230049-FRA, cache-bur-kbur8200095-BUR
```
</details>
