### ISSUE TITLE
[feature request]: Dark mode

### ISSUE THREAD

**Issue by jimmywarting** [jsdelivr/jsdelivr#18500]
### Is your feature request related to a problem? Please describe.

site is to bright at night

### Describe the solution you would like.

For the website to support dark mode and hopefully also make use of `color-scheme` with either of this solutions:

`<meta name="color-scheme" content="dark light">`
```css
@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;
  }
}
```

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.
