### ISSUE TITLE
Bug: Combined requests are broken for font stylesheets

### ISSUE THREAD

**Issue by smiley** [jsdelivr/jsdelivr#2018]
Hey,

I tried to [use combined requests](//cdn.jsdelivr.net/g/bootstrap@3.2.0%28css/bootstrap.min.css%29,fontawesome@4.2.0,octicons@2.1.2) (the `/g/...` feature) with [font-awesome](/FortAwesome/Font-Awesome) & [Octicons](//octicons.github.com), and I encountered a bug: the internal font-fetching causes a URL aliasing issue: (that the browser wrongly brings up as a CORS issue)

``` css
@font-face {
    font-family: 'FontAwesome';
    src: url('../fonts/fontawesome-webfont.eot?v=4.2.0');
    src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.2.0') format('embedded-opentype'),url('../fonts/fontawesome-webfont.woff?v=4.2.0') format('woff'),url('../fonts/fontawesome-webfont.ttf?v=4.2.0') format('truetype'),url('../fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

Since the request (obviously) doesn't return some form of redirect, when any browser (tested on Chrome 38/39, Firefox 32 & IE 11) tries to fetch `../fonts/fontawesome-webfont.woff?v=4.2.0`, it **actually** fetches [`http://cdn.jsdelivr.net/fonts/fontawesome-webfont.woff?v=4.2.0`](//cdn.jsdelivr.net/fonts/fontawesome-webfont.woff?v=4.2.0).

I'm not sure how this can be fixed without manual fixes to files or somehow smartly-replacing these relative URLs for `/g/` requests (which potentially cancels out any CDN benefit). Maybe for now, grouping-requests could automatically fail when encountering a file that includes fonts? (By pre-sorting them)
