### ISSUE TITLE
Possible workaround of problem with jsDelivr file combiner

### ISSUE THREAD

**Issue by thekondrashov** [jsdelivr/jsdelivr#3176]
Hello.
I know about the problem with jsDelivr file combiner with css files that load images or another assets ([#452](https://github.com/jsdelivr/jsdelivr/issues/452), [#500](https://github.com/jsdelivr/jsdelivr/issues/500), [#666](https://github.com/jsdelivr/jsdelivr/issues/666), [#1222](https://github.com/jsdelivr/jsdelivr/issues/1222), [#2014](https://github.com/jsdelivr/jsdelivr/issues/2014), [#2018](https://github.com/jsdelivr/jsdelivr/issues/2018), [#2656](https://github.com/jsdelivr/jsdelivr/issues/2656)).
I offer my solution to this problem (I understand that this is not the best idea). The idea: to create a new project, which includes css files with the overridden styles for fontawesome, bootstrap and other similar projects.
I created a [test project](https://github.com/thekondrashov/jsdelivr-assetsfix) with the following structure:
- [**fontawesome/**](https://github.com/thekondrashov/jsdelivr-assetsfix/tree/master/fontawesome)
	- [**latest/**](https://github.com/thekondrashov/jsdelivr-assetsfix/tree/master/fontawesome/latest)
		- [assets.css](https://github.com/thekondrashov/jsdelivr-assetsfix/blob/master/fontawesome/latest/assets.css) — This is a copy of a workaround from a 4.2.0/ folder. This should be overwritten when the fontawesome will release a new version.
	- [**4.2.0/**](https://github.com/thekondrashov/jsdelivr-assetsfix/tree/master/fontawesome/4.2.0)
		- [assets.css](https://github.com/thekondrashov/jsdelivr-assetsfix/blob/master/fontawesome/4.2.0/assets.css) — This is a compressed version of css workaround, which corresponds to original 4.2.0 bootstrap version.
	- [**4.1.0/**](https://github.com/thekondrashov/jsdelivr-assetsfix/tree/master/fontawesome/4.1.0)
		- [assets.css](https://github.com/thekondrashov/jsdelivr-assetsfix/blob/master/fontawesome/4.1.0/assets.css) — This is a compressed version of css workaround, which corresponds to version 4.1.0.
	- [**{x.x.x}/**](https://github.com/thekondrashov/jsdelivr-assetsfix/tree/master/fontawesome) — And other (older) versions of which are in the [repository jsDelivr](http://api.jsdelivr.com/v1/jsdelivr/libraries?name=fontawesome)
- [**bootstrap/**](https://github.com/thekondrashov/jsdelivr-assetsfix/tree/master/bootstrap)
— The structure is completely analogous to the previous one.
- [**{other}/**](https://github.com/thekondrashov/jsdelivr-assetsfix)
— And any similar projects.

This structure will allow you to access the files with a single request like this (with normalize for example):
`//cdn.jsdelivr.net/g/normalize,fontawesome@4.2.0,jsdelivr-assetsfix(fontawesome/4.2.0/assets.css)`
In this case, the version of the project with the workaround is not important. And you can always specify the latest version of "jsdelivr-assetsfix" project.

If you want to specify the latest version of fontawesome, use this:
`//cdn.jsdelivr.net/g/normalize,fontawesome,jsdelivr-assetsfix(fontawesome/latest/assets.css)`
(Of course this will require a manual update when a new version of the font will appear.)

In the case of the version aliasing, you can create the appropriate directories:
`//cdn.jsdelivr.net/g/normalize,fontawesome@4,jsdelivr-assetsfix(fontawesome/4/assets.css)`
(You only need to create the directory "fontawesome/4/". And update if necessary.)

The example code with the workaround (for latest(4.2.0) version of fontawesome):
```css
@font-face {
  /* I have not found a better solution, and simply create a new font-family */
  font-family: 'FontAwesome Fallback';
  src: url('https://cdn.jsdelivr.net/fontawesome/4.2.0/fonts/fontawesome-webfont.eot?v=4.2.0');
  src: url('https://cdn.jsdelivr.net/fontawesome/4.2.0/fonts/fontawesome-webfont.eot?#iefix&v=4.2.0') format('embedded-opentype'),
       url('https://cdn.jsdelivr.net/fontawesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0') format('woff'),
       url('https://cdn.jsdelivr.net/fontawesome/4.2.0/fonts/fontawesome-webfont.ttf?v=4.2.0') format('truetype'),
       url('https://cdn.jsdelivr.net/fontawesome/4.2.0/fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
.fa {
  /* Override font-family with "!important" */
  font-family: 'FontAwesome Fallback'!important;
}
```
This technique allows you to specify a workaround anywhere in the url, even before the main file:
`//cdn.jsdelivr.net/g/jsdelivr-assetsfix(fontawesome/latest/assets.css),normalize,fontawesome`

What do you think about this mad idea?

And please replace the example on README.md page:
`//cdn.jsdelivr.net/g/angularui@0.4.0(angular-ui.min.css),fontawesome@4.0.3(css/font-awesome.min.css)`
(fontawesome assets not loading)

/ Sorry for my English /
