### ISSUE TITLE
Font reference broken with Bootstrap

### ISSUE THREAD

**Issue by passcod** [jsdelivr/jsdelivr#666]
:japanese_ogre: When using combined files for loading bootstrap CSS, the `@font-face` urls aren't set properly.

I'm using `//cdn.jsdelivr.net/g/bootstrap@3(css/bootstrap.min.css+css/bootstrap-theme.min.css)`, and getting:

``` css
@font-face{
    font-family:'Glyphicons Halflings';
    src:url("http://cdn.jsdelivr.net/g/bootstrap@3(css/bootstrap.min.css+css/../fonts/glyphicons-halflings-regular.eot");
    src:url("http://cdn.jsdelivr.net/g/bootstrap@3(css/bootstrap.min.css+css/../fonts/glyphicons-halflings-regular.eot?#iefix") format('embedded-opentype'),url("http://cdn.jsdelivr.net/g/bootstrap@3(css/bootstrap.min.css+css/../fonts/glyphicons-halflings-regular.woff") format('woff'),url("http://cdn.jsdelivr.net/g/bootstrap@3(css/bootstrap.min.css+css/../fonts/glyphicons-halflings-regular.ttf") format('truetype'),url("http://cdn.jsdelivr.net/g/bootstrap@3(css/bootstrap.min.css+css/../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular") format('svg')
}
```
1. This results in a 404.
2. Even if it worked, it wouldn't be the right thing: as per the docs, it would combine the `bootstrap.min.css` and `glyphicons-halflings-regular.ext` into one unusable file _and_ serve it with `application/javascript`.

I'm not sure how these urls are generated, but clearly it's not compatible with `/g/` use.
